import type { Prisma } from "@prisma/client";

/**
 * Full Thai SME Chart of Accounts for WIND CLINIC.
 *
 * Hierarchical: header accounts (is_postable=false) group postable leaves
 * (is_postable=true). Postable leaves are the only accounts that can appear
 * in a JournalLine.
 *
 * All 90 accounts from spec 10-seed-data.md §1.
 */
export const ACCOUNTS: Prisma.AccountCreateInput[] = [
  // ═══════ 1xxxx ASSETS ═══════
  { code: "10000", name_en: "Assets", name_th: "สินทรัพย์", type: "ASSET", is_postable: false },

  {
    code: "11000",
    name_en: "Current Assets",
    name_th: "สินทรัพย์หมุนเวียน",
    type: "ASSET",
    is_postable: false,
    parent_code: "10000",
  },
  { code: "11010", name_en: "Cash on Hand", name_th: "เงินสด", type: "ASSET", parent_code: "11000" },
  {
    code: "11020",
    name_en: "KBank Current",
    name_th: "เงินฝากธนาคาร - กสิกรไทย กระแสรายวัน",
    type: "ASSET",
    parent_code: "11000",
  },
  {
    code: "11030",
    name_en: "SCB Savings",
    name_th: "เงินฝากธนาคาร - ไทยพาณิชย์ ออมทรัพย์",
    type: "ASSET",
    parent_code: "11000",
  },
  { code: "11100", name_en: "Petty Cash", name_th: "เงินสดย่อย", type: "ASSET", parent_code: "11000" },

  {
    code: "12000",
    name_en: "Receivables",
    name_th: "ลูกหนี้",
    type: "ASSET",
    is_postable: false,
    parent_code: "10000",
  },
  {
    code: "12010",
    name_en: "Accounts Receivable - Trade",
    name_th: "ลูกหนี้การค้า",
    type: "ASSET",
    parent_code: "12000",
  },
  {
    code: "12020",
    name_en: "Other Receivables",
    name_th: "ลูกหนี้อื่น",
    type: "ASSET",
    parent_code: "12000",
  },

  {
    code: "13000",
    name_en: "Inventory",
    name_th: "สินค้าคงเหลือ",
    type: "ASSET",
    is_postable: false,
    parent_code: "10000",
  },
  {
    code: "13010",
    name_en: "Inventory - Products",
    name_th: "สินค้าคงเหลือ - ผลิตภัณฑ์",
    type: "ASSET",
    parent_code: "13000",
  },
  {
    code: "13020",
    name_en: "Inventory - Supplies",
    name_th: "สินค้าคงเหลือ - วัสดุสิ้นเปลือง",
    type: "ASSET",
    parent_code: "13000",
  },

  {
    code: "14000",
    name_en: "Tax Assets",
    name_th: "ภาษีในสินทรัพย์",
    type: "ASSET",
    is_postable: false,
    parent_code: "10000",
  },
  {
    code: "14010",
    name_en: "VAT Receivable (Input VAT)",
    name_th: "ภาษีซื้อ",
    type: "ASSET",
    parent_code: "14000",
  },
  {
    code: "14020",
    name_en: "Withholding Tax Receivable",
    name_th: "ภาษีถูกหัก ณ ที่จ่าย",
    type: "ASSET",
    parent_code: "14000",
  },

  {
    code: "15000",
    name_en: "Other Current Assets",
    name_th: "สินทรัพย์หมุนเวียนอื่น",
    type: "ASSET",
    is_postable: false,
    parent_code: "10000",
  },
  {
    code: "15010",
    name_en: "Prepaid Expenses",
    name_th: "ค่าใช้จ่ายจ่ายล่วงหน้า",
    type: "ASSET",
    parent_code: "15000",
  },
  { code: "15020", name_en: "Deposits", name_th: "เงินมัดจำ", type: "ASSET", parent_code: "15000" },

  {
    code: "16000",
    name_en: "Non-current Assets",
    name_th: "สินทรัพย์ไม่หมุนเวียน",
    type: "ASSET",
    is_postable: false,
    parent_code: "10000",
  },
  { code: "16010", name_en: "Equipment", name_th: "อุปกรณ์", type: "ASSET", parent_code: "16000" },
  {
    code: "16011",
    name_en: "Medical Equipment",
    name_th: "อุปกรณ์การแพทย์",
    type: "ASSET",
    parent_code: "16000",
  },
  {
    code: "16012",
    name_en: "Furniture & Fixtures",
    name_th: "เฟอร์นิเจอร์และอุปกรณ์ตกแต่ง",
    type: "ASSET",
    parent_code: "16000",
  },
  {
    code: "16020",
    name_en: "Accumulated Depreciation",
    name_th: "ค่าเสื่อมราคาสะสม",
    type: "ASSET",
    parent_code: "16000",
  },

  // ═══════ 2xxxx LIABILITIES ═══════
  {
    code: "20000",
    name_en: "Liabilities",
    name_th: "หนี้สิน",
    type: "LIABILITY",
    is_postable: false,
  },

  {
    code: "21000",
    name_en: "Current Liabilities",
    name_th: "หนี้สินหมุนเวียน",
    type: "LIABILITY",
    is_postable: false,
    parent_code: "20000",
  },
  {
    code: "21010",
    name_en: "Accounts Payable - Trade",
    name_th: "เจ้าหนี้การค้า",
    type: "LIABILITY",
    parent_code: "21000",
  },
  {
    code: "21020",
    name_en: "Other Payables",
    name_th: "เจ้าหนี้อื่น",
    type: "LIABILITY",
    parent_code: "21000",
  },
  {
    code: "21030",
    name_en: "Doctor Commission Payable",
    name_th: "ค่านายหน้าหมอค้างจ่าย",
    type: "LIABILITY",
    parent_code: "21000",
  },
  {
    code: "21040",
    name_en: "Accrued Expenses",
    name_th: "ค่าใช้จ่ายค้างจ่าย",
    type: "LIABILITY",
    parent_code: "21000",
  },

  {
    code: "21100",
    name_en: "Tax Payables",
    name_th: "ภาษีค้างจ่าย",
    type: "LIABILITY",
    is_postable: false,
    parent_code: "21000",
  },
  {
    code: "21110",
    name_en: "VAT Payable (Output VAT)",
    name_th: "ภาษีขาย",
    type: "LIABILITY",
    parent_code: "21100",
  },
  {
    code: "21120",
    name_en: "Withholding Tax Payable",
    name_th: "ภาษีหัก ณ ที่จ่าย",
    type: "LIABILITY",
    parent_code: "21100",
  },
  {
    code: "21130",
    name_en: "Income Tax Payable",
    name_th: "ภาษีเงินได้นิติบุคคลค้างจ่าย",
    type: "LIABILITY",
    parent_code: "21100",
  },

  {
    code: "21200",
    name_en: "Customer Liabilities",
    name_th: "หนี้สินต่อลูกค้า",
    type: "LIABILITY",
    is_postable: false,
    parent_code: "21000",
  },
  {
    code: "21210",
    name_en: "Customer Deposits",
    name_th: "เงินรับล่วงหน้าจากลูกค้า",
    type: "LIABILITY",
    parent_code: "21200",
  },
  {
    code: "21220",
    name_en: "Unearned Revenue (Packages)",
    name_th: "รายได้รับล่วงหน้า (แพ็กเกจ)",
    type: "LIABILITY",
    parent_code: "21200",
  },

  // ═══════ 3xxxx EQUITY ═══════
  { code: "30000", name_en: "Equity", name_th: "ส่วนของผู้ถือหุ้น", type: "EQUITY", is_postable: false },
  {
    code: "31010",
    name_en: "Owner's Capital",
    name_th: "ทุนเรือนหุ้น",
    type: "EQUITY",
    parent_code: "30000",
  },
  {
    code: "31020",
    name_en: "Retained Earnings",
    name_th: "กำไรสะสม",
    type: "EQUITY",
    parent_code: "30000",
  },
  {
    code: "31030",
    name_en: "Current Year Earnings",
    name_th: "กำไร(ขาดทุน)สุทธิประจำปี",
    type: "EQUITY",
    parent_code: "30000",
  },

  // ═══════ 4xxxx REVENUE ═══════
  { code: "40000", name_en: "Revenue", name_th: "รายได้", type: "REVENUE", is_postable: false },

  {
    code: "41000",
    name_en: "Service Revenue",
    name_th: "รายได้ค่าบริการ",
    type: "REVENUE",
    is_postable: false,
    parent_code: "40000",
  },
  {
    code: "41010",
    name_en: "Service Revenue - Botox",
    name_th: "รายได้ - Botox",
    type: "REVENUE",
    parent_code: "41000",
  },
  {
    code: "41020",
    name_en: "Service Revenue - Filler",
    name_th: "รายได้ - Filler",
    type: "REVENUE",
    parent_code: "41000",
  },
  {
    code: "41030",
    name_en: "Service Revenue - Laser",
    name_th: "รายได้ - เลเซอร์",
    type: "REVENUE",
    parent_code: "41000",
  },
  {
    code: "41040",
    name_en: "Service Revenue - Skincare",
    name_th: "รายได้ - ทรีตเมนต์ผิว",
    type: "REVENUE",
    parent_code: "41000",
  },
  {
    code: "41050",
    name_en: "Service Revenue - Body",
    name_th: "รายได้ - ทรีตเมนต์รูปร่าง",
    type: "REVENUE",
    parent_code: "41000",
  },
  {
    code: "41090",
    name_en: "Service Revenue - Other",
    name_th: "รายได้ - บริการอื่น",
    type: "REVENUE",
    parent_code: "41000",
  },

  {
    code: "42000",
    name_en: "Product Sales",
    name_th: "รายได้ขายสินค้า",
    type: "REVENUE",
    is_postable: false,
    parent_code: "40000",
  },
  {
    code: "42010",
    name_en: "Product Sales - Skincare",
    name_th: "ขายผลิตภัณฑ์ดูแลผิว",
    type: "REVENUE",
    parent_code: "42000",
  },
  {
    code: "42020",
    name_en: "Product Sales - Supplements",
    name_th: "ขายอาหารเสริม",
    type: "REVENUE",
    parent_code: "42000",
  },

  {
    code: "49000",
    name_en: "Other Income",
    name_th: "รายได้อื่น",
    type: "REVENUE",
    is_postable: false,
    parent_code: "40000",
  },
  {
    code: "49010",
    name_en: "Other Income",
    name_th: "รายได้อื่น",
    type: "REVENUE",
    parent_code: "49000",
  },

  // ═══════ 5xxxx COST OF SALES ═══════
  {
    code: "50000",
    name_en: "Cost of Sales",
    name_th: "ต้นทุนขายและบริการ",
    type: "EXPENSE",
    is_postable: false,
  },

  {
    code: "51000",
    name_en: "Cost of Services",
    name_th: "ต้นทุนบริการ",
    type: "EXPENSE",
    is_postable: false,
    parent_code: "50000",
  },
  {
    code: "51010",
    name_en: "Products Consumed",
    name_th: "ต้นทุนผลิตภัณฑ์ที่ใช้",
    type: "EXPENSE",
    parent_code: "51000",
  },
  {
    code: "51020",
    name_en: "Doctor Commission",
    name_th: "ค่านายหน้าแพทย์",
    type: "EXPENSE",
    parent_code: "51000",
  },
  {
    code: "51030",
    name_en: "Therapist Commission",
    name_th: "ค่านายหน้าเทอราพิสต์",
    type: "EXPENSE",
    parent_code: "51000",
  },

  {
    code: "52000",
    name_en: "Inventory Variance",
    name_th: "การปรับปรุงสินค้าคงเหลือ",
    type: "EXPENSE",
    is_postable: false,
    parent_code: "50000",
  },
  {
    code: "52010",
    name_en: "Inventory Loss - Damage",
    name_th: "ขาดทุนจากสินค้าเสียหาย",
    type: "EXPENSE",
    parent_code: "52000",
  },
  {
    code: "52020",
    name_en: "Inventory Loss - Expired",
    name_th: "ขาดทุนจากสินค้าหมดอายุ",
    type: "EXPENSE",
    parent_code: "52000",
  },
  {
    code: "52030",
    name_en: "Inventory Loss - Theft",
    name_th: "ขาดทุนจากสินค้าสูญหาย",
    type: "EXPENSE",
    parent_code: "52000",
  },
  {
    code: "52040",
    name_en: "Inventory Variance - Count",
    name_th: "ผลต่างจากการตรวจนับ",
    type: "EXPENSE",
    parent_code: "52000",
  },

  // ═══════ 6xxxx OPERATING EXPENSES ═══════
  {
    code: "60000",
    name_en: "Operating Expenses",
    name_th: "ค่าใช้จ่ายดำเนินงาน",
    type: "EXPENSE",
    is_postable: false,
  },

  {
    code: "61000",
    name_en: "Personnel",
    name_th: "ค่าใช้จ่ายเกี่ยวกับบุคลากร",
    type: "EXPENSE",
    is_postable: false,
    parent_code: "60000",
  },
  {
    code: "61010",
    name_en: "Salary Expense",
    name_th: "เงินเดือน",
    type: "EXPENSE",
    parent_code: "61000",
  },
  { code: "61011", name_en: "Wages", name_th: "ค่าจ้าง", type: "EXPENSE", parent_code: "61000" },
  {
    code: "61012",
    name_en: "Social Security Expense",
    name_th: "ประกันสังคม - นายจ้าง",
    type: "EXPENSE",
    parent_code: "61000",
  },
  {
    code: "61013",
    name_en: "Bonus & Incentive",
    name_th: "โบนัส",
    type: "EXPENSE",
    parent_code: "61000",
  },

  {
    code: "61100",
    name_en: "Premises",
    name_th: "ค่าใช้จ่ายเกี่ยวกับสถานที่",
    type: "EXPENSE",
    is_postable: false,
    parent_code: "60000",
  },
  { code: "61110", name_en: "Rent Expense", name_th: "ค่าเช่า", type: "EXPENSE", parent_code: "61100" },
  {
    code: "61120",
    name_en: "Utilities - Electricity",
    name_th: "ค่าไฟฟ้า",
    type: "EXPENSE",
    parent_code: "61100",
  },
  {
    code: "61130",
    name_en: "Utilities - Water",
    name_th: "ค่าน้ำประปา",
    type: "EXPENSE",
    parent_code: "61100",
  },
  {
    code: "61140",
    name_en: "Utilities - Internet/Phone",
    name_th: "ค่าอินเทอร์เน็ตและโทรศัพท์",
    type: "EXPENSE",
    parent_code: "61100",
  },

  {
    code: "61200",
    name_en: "Marketing",
    name_th: "ค่าใช้จ่ายการตลาด",
    type: "EXPENSE",
    is_postable: false,
    parent_code: "60000",
  },
  {
    code: "61210",
    name_en: "Marketing - Online",
    name_th: "การตลาดออนไลน์",
    type: "EXPENSE",
    parent_code: "61200",
  },
  {
    code: "61220",
    name_en: "Marketing - Offline",
    name_th: "การตลาดออฟไลน์",
    type: "EXPENSE",
    parent_code: "61200",
  },
  {
    code: "61230",
    name_en: "Marketing - Influencer",
    name_th: "อินฟลูเอนเซอร์",
    type: "EXPENSE",
    parent_code: "61200",
  },

  {
    code: "61300",
    name_en: "Banking",
    name_th: "ค่าใช้จ่ายธนาคาร",
    type: "EXPENSE",
    is_postable: false,
    parent_code: "60000",
  },
  {
    code: "61310",
    name_en: "Bank Fees",
    name_th: "ค่าธรรมเนียมธนาคาร",
    type: "EXPENSE",
    parent_code: "61300",
  },
  {
    code: "61320",
    name_en: "Card Processing Fees",
    name_th: "ค่าธรรมเนียมบัตรเครดิต",
    type: "EXPENSE",
    parent_code: "61300",
  },

  {
    code: "61400",
    name_en: "Professional Services",
    name_th: "ค่าบริการวิชาชีพ",
    type: "EXPENSE",
    is_postable: false,
    parent_code: "60000",
  },
  {
    code: "61410",
    name_en: "Accounting & Legal",
    name_th: "ค่าบัญชีและกฎหมาย",
    type: "EXPENSE",
    parent_code: "61400",
  },
  {
    code: "61420",
    name_en: "Software & Subscriptions",
    name_th: "ค่าซอฟต์แวร์",
    type: "EXPENSE",
    parent_code: "61400",
  },

  {
    code: "61500",
    name_en: "Other Expenses",
    name_th: "ค่าใช้จ่ายอื่น",
    type: "EXPENSE",
    is_postable: false,
    parent_code: "60000",
  },
  {
    code: "61510",
    name_en: "Office Supplies",
    name_th: "อุปกรณ์สำนักงาน",
    type: "EXPENSE",
    parent_code: "61500",
  },
  {
    code: "61520",
    name_en: "Travel & Transport",
    name_th: "ค่าเดินทาง",
    type: "EXPENSE",
    parent_code: "61500",
  },
  {
    code: "61530",
    name_en: "Training & Development",
    name_th: "ค่าฝึกอบรม",
    type: "EXPENSE",
    parent_code: "61500",
  },
  {
    code: "61540",
    name_en: "Depreciation Expense",
    name_th: "ค่าเสื่อมราคา",
    type: "EXPENSE",
    parent_code: "61500",
  },

  {
    code: "69010",
    name_en: "Miscellaneous Expense",
    name_th: "ค่าใช้จ่ายเบ็ดเตล็ด",
    type: "EXPENSE",
    parent_code: "60000",
  },
];
