-- Add DOCTOR_COMMISSION and WIND_VISIT values to JESourceType enum
ALTER TYPE "JESourceType" ADD VALUE IF NOT EXISTS 'DOCTOR_COMMISSION';
ALTER TYPE "JESourceType" ADD VALUE IF NOT EXISTS 'WIND_VISIT';
